version: "3.0"
services:
  parser:
    image: haitranquangofficial/graduation:parser
    restart: always
    ports:
      - 5000:5000
    networks:
      - grnet
networks:
  grnet:
    name: gr_network